# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gemini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-gemini-app
  template:
    metadata:
      labels:
        app: flask-gemini-app
    spec:
      containers:
      - name: flask-gemini-app
        image: gcr.io/latha-424019/flask-gemini-app
        ports:
        - containerPort: 5000
